include:
  - ../../../conll2003/_task.yaml
  - ../_model.yaml

experiment_group: gemma-4-e4b-it_outlook
experiment_name: gemma-4-e4b-it_outlook_conll2003_00_zeroshot

grid:

  seed: [42]

fixed:

  output.root: results/outlook/gemma-4-e4b-it/conll2003/00_zeroshot

  adaptation: none

  dataset.subset_size: 1
  training.learning_rate: 5e-05
  training.epochs: 1
