include:
  - ../../../conll2003/_task.yaml
  - ../_model.yaml

experiment_group: deepseek-r1-distill-qwen-7b_outlook
experiment_name: deepseek-r1-distill-qwen-7b_outlook_conll2003_00_zeroshot

grid:

  seed: [42]

fixed:

  output.root: results/outlook/deepseek-r1-distill-qwen-7b/conll2003/00_zeroshot

  adaptation: none

  dataset.subset_size: 1
  training.learning_rate: 5e-05
  training.epochs: 1
