include:
  - ../../../squad/_task.yaml
  - ../_model.yaml

experiment_group: mistral-7b-instruct-v0.3_outlook
experiment_name: mistral-7b-instruct-v0.3_outlook_squad_00_zeroshot

grid:

  seed: [42]

fixed:

  output.root: results/outlook/mistral-7b-instruct-v0.3/squad/00_zeroshot

  adaptation: none

  dataset.subset_size: 1
  training.learning_rate: 5e-05
  training.epochs: 1
