"""Generate one SLURM array job per outlook model.

Writes slurm/outlook/run_<model>_outlook.slurm. Each array task is a
(config, grid index) pair, flattened over all datasets and blocks:
44 tasks per model (4 datasets x 11 runs: zero-shot, FFT and 3 targets
x 3 rank/alpha tiers), at most 4 running at once. Single-point
configs use index 0.

Usage:
    python -m scripts.generate_outlook_slurm
"""

import os


MODELS = [
    "gemma-4-e4b-it", "gpt-oss-20b", "deepseek-r1-distill-qwen-7b",
    "llama-3.1-8b-instruct", "mistral-7b-instruct-v0.3",
]
DATASETS = ["mnli", "squad", "conll2003", "gsm8k"]
TARGETS = ["qv", "attention", "full"]
BLOCK_ID = {"qv": "10", "attention": "11", "full": "12"}

CONFIG_ROOT = "configs/outlook"
RESULTS_ROOT = "results/outlook"
SLURM_OUT_DIR = "slurm/outlook"

CONCURRENCY = 4
TIME_LIMIT = "08:00:00"  # Same limit as the main study.


def _entries_for_model(model):
    """Return [(config_path, grid_index), ...] for all runs of `model`.

    Ordered by dataset, then block, as in generate_outlook_configs.py.
    """
    entries = []

    for dataset in DATASETS:

        base = f"{CONFIG_ROOT}/{model}/{dataset}"

        entries.append((f"{base}/00_zeroshot.yaml", 0))
        entries.append((f"{base}/01_fft.yaml", 0))

        for target in TARGETS:
            config = f"{base}/{BLOCK_ID[target]}_main_{target}.yaml"
            for tier_index in range(3):  # low, moderate, extreme
                entries.append((config, tier_index))

    return entries


def slurm_yaml(model):

    entries = _entries_for_model(model)
    n = len(entries)

    configs_lines = "\n".join(f'  "{c}"' for c, _ in entries)
    indices_lines = "\n".join(f"  {i}" for _, i in entries)

    return f"""#!/bin/bash
#SBATCH --job-name={model}-outlook

#SBATCH --partition=kisski
#SBATCH --gres=gpu:1

#SBATCH --cpus-per-task=8
#SBATCH --mem=64G

#SBATCH --time={TIME_LIMIT}

#SBATCH --array=0-{n - 1}%{CONCURRENCY}

#SBATCH --output={RESULTS_ROOT}/{model}/logs/%x_%A_%a.out

source ~/lora-thesis/lora-env/bin/activate

cd ~/lora-thesis

mkdir -p {RESULTS_ROOT}/{model}/logs/

#
# {n} array tasks = 4 datasets x 11 runs/dataset (1 zeroshot + 1 fft +
# 3 targets x 3 rank/alpha tiers) -- generated by
# scripts/generate_outlook_slurm.py, not hand-written; regenerate rather
# than hand-edit if configs/outlook/{model}/ changes. Every task passes
# an explicit grid index (0 for the single-point zeroshot/fft configs
# too), same convention the main study's own multi-point-grid .slurm
# files use.
#

CONFIGS=(
{configs_lines}
)

INDICES=(
{indices_lines}
)

python -m src.experiments.runner "${{CONFIGS[$SLURM_ARRAY_TASK_ID]}}" "${{INDICES[$SLURM_ARRAY_TASK_ID]}}"
"""


def main():

    os.makedirs(SLURM_OUT_DIR, exist_ok=True)

    written = []

    for model in MODELS:

        path = f"{SLURM_OUT_DIR}/run_{model}_outlook.slurm"

        with open(path, "w") as f:
            f.write(slurm_yaml(model))

        written.append(path)
        print(f"wrote {path} ({len(_entries_for_model(model))} array tasks)")

    # Batch submit wrappers live in slurm/scripts/, like the others.
    wrapper_path = "slurm/scripts/run_outlook.sh"
    os.makedirs("slurm/scripts", exist_ok=True)
    with open(wrapper_path, "w") as f:
        f.write("#!/bin/bash\n\n")
        for model in MODELS:
            f.write(f"sbatch {SLURM_OUT_DIR}/run_{model}_outlook.slurm\n")
    os.chmod(wrapper_path, 0o750)  # Same as the other wrappers.

    print(f"wrote {wrapper_path}")


if __name__ == "__main__":
    main()
